source "$MYZSH_DIR/config/myzsh/env"
export PATH=$HOME/.myzsh/bin:$PATH
fpath=($MYZSH_DIR/lib $fpath)
source "$MYZSH_DIR/config/myzsh/autoload"
source "$MYZSH_DIR/start/lib.sh"
source "$MYZSH_DIR/config/myzsh/language"
source "$MYZSH_DIR/config/myzsh/HISTFILE"
source "$MYZSH_DIR/start/history.sh"
source "$MYZSH_DIR/config/myzsh/alias"
source "$MYZSH_DIR/lib/zsh-defer.plugin.zsh"
source "$MYZSH_DIR/config/myzsh/ZSH_THEME"
source "$MYZSH_DIR/config/myzsh/ZSH_THEME_CONFIG"
source "$MYZSH_DIR/start/theme.sh"
source "$MYZSH_DIR/config/myzsh/plugins"
zsh-defer source "$MYZSH_DIR/start/plugins.sh"